image: git-service.ait.ac.at:8010/sct-crypto/students/2024_naves/docker-images/rust-faest:latest

stages:
  - build
  - test

build:
  stage: build
  script:
    - cargo build --release

build-all-features:
  stage: build
  script:
    - cargo build --release --all-features

build-bench:
  stage: build
  script:
    - cargo build --bench benchmark_faest_rs

clippy:
  stage: test
  script:
    - cargo clippy -- -D warnings

fmt:
  stage: test
  script:
    - cargo fmt -- --check

test:
  stage: test
  script:
    - cargo test --release

test-all-features:
  stage: test
  script:
    - cargo test --release --all-features

test-example-simple:
  stage: test
  script:
    - cargo run --release --example simple
