image: git-service.ait.ac.at:8010/sct-crypto/students/2024_naves/docker-images/rust-faest:latest

stages:
  - build
  - test

build:
  stage: build
  script:
    - cargo build --no-default-features
    - cargo build
    - cargo build --all-features
    - cargo build --bench benchmark_faest_rs

clippy:
  stage: test
  script:
    - cargo clippy --no-default-features -- -D warnings
    - cargo clippy -- -D warnings
    - cargo clippy --all-features -- -D warnings

fmt:
  stage: test
  script:
    - cargo fmt -- --check

test:
  stage: test
  script:
    - cargo test --release --no-default-features
    - cargo test --release
    - cargo test --release --all-features
    - cargo run --release --example simple

bench:
  stage: test
  script:
    - cargo bench
