[package]
name = "faest"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aes = "0.8.4"
ctr = "0.9.2"
rand = "0.8.5"
sha3 = "0.10.8"

[dev-dependencies]
num-bigint = "0.4.4"
